ODP-1841: Hive - HMS | Unable to run hive queries (#35)
* ODP-1838: handling NoClassDefFoundError for com.google.guava:failureaccess for Hive-4.0.0

(cherry picked from commit ed5f688d5078ea51cf8679a746d06460d57904af)
(cherry picked from commit a2fb224611b05f591160288f41b05a58555288c2)

* undo partial ODP-1640

---------